<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Widgets' => 'Γραφικά στοιχεία',
    'Widget' => 'Γραφικό στοιχείο',
    'Widget Type ID' => 'Τύπος Γραφικού Στοιχείου',
    'Module Name' => 'Όνομα Module',
    'Widget Name' => 'Όνομα Γραφικού Στοιχείου',
    'Widget class' => 'Κλάση Γραφικού στοιχείου',
    'Description' => 'Περιγραφή',
    'The Widgets caregorized to Frontend and Backend environment ( and Module tabs ) by Module Name that exist within Position' => 'Τα Widgets έχουν ταξινομηθεί στο περιβάλλον Frontend και Backend (και στις καρτέλες Module) από το όνομα του Widget που υπάρχει στη Position',
    'The Position may belong to a different Module Name than the module name that exists within the Widget type' => 'Η θέση μπορεί να ανήκει σε διαφορετικό Module name από το Module name που υπάρχει μέσα στον τύπο του Widget',
    'Widgets Types' => 'Τύποι γραφικών στοιχείων',
    'Positions' => 'Θέσεις',
    'Layouts' => 'Διατάξεις',
    'List of Widngets' => 'Λίστα Γραφικών στοιχείων',
    'Create new Widget' => 'Δημιουργία νέου Γραφικού στοιχείου',
    'Widget Type' => 'Τύπος Γραφικού στοιχείου',
    'Name' => 'Όνομα',
    'Position' => 'Θέση',
    'Publish' => 'Δημοσίευση',
    'Config' => 'Διαμόρφωση',
    'Rules' => 'Κανόνες',
    'Created At' => 'Ημερομηνία δημιουργίας',
    'Updated At' => 'Ημερομηνία Αλλαγής',
    'Widget Technical Name' => 'Τεχν.όνομα Γραφ.Στοιχείου',
    'Environment' => 'Περιβάλλον',
    'List of Widgets Types' => 'Λίστα Τύπων Γραφικών Στοιχείων',
    'Create new Type' => 'Δημιουργία νέου Τύπου',
    'Create Type' => 'Δημιουργία Τύπου',
    'Save' => 'Αποθήκευση',
    'Save Changes' => 'Αποθήκευση Αλλαγών',
    'Widget Types' => 'Τύποι Γραφ.Στοιχείων',
    'Update' => 'Αλλαγή',
    'Delete' => 'Διαγραφή',
    'View' => 'Εμφάνιση',
    'View Widget Type : {title} ' => 'Εμφάνιση Γραφικού Στοιχείου : {title} ',
    'Widgets with type : {type} ' => 'Γραφικά Στοιχεία με τύπο : {type} ',
    'Are you sure you want to delete this item ?' => 'Είσαι σίγουρος πως θέλεις να διαγράψεις αυτό το αντικείμενο ?',
    'Update Type' => 'Αλλαγή Τύπου',
    'List of Positions' => 'Λίστα Θέσεων',
    'Create new Position' => 'Δημιουργία νέας Θέσης',
    'Rebuild Sort Order' => 'Aνοικοδομήστε τη σειρά ταξινόμησης',
    'Sort Order' => 'Ταξινόμηση',
    'Rebuild' => 'Ανοικοδόμηση',
    'Position Technical Name' => 'Τεχνικό όνομα Θέσης',
    'Delete position ! Are yoy sure ?' => 'Διαγραφή Θέσης ! Είσαι σίγουρος ?',
    'Published' => 'Δημοσιευμένο',
    'Unpublished' => 'Αδημοσίευτο',
    'List of Layouts' => 'Λίστα Διατάξεων',
    'Create new Layout' => 'Δημιουργία νέας Διάταξης',
    'Technical Name' => 'Τεχνικό Όνομα',
    'Html Layout' => 'Html Διάταξης',
    'Available Positions' => 'Διαθέσιμες Θέσεις',
    'View Position : {title}' => 'Εμφάνιση Θέσης : {title}',
    'View Layout : {title}' => 'Εμφάνιση Διάταξης : {title}',
    'Update Layout' => 'Αλλαγή Διάταξης',
    'Preview' => 'Προεπισκόπηση',
    'Create Layout' => 'Δημιουργία Διάταξης',
    'Create Widget' => 'Δημιουργία Γραφικού Στοιχείου',
    
];
