<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Widget Type ID' => 'Τύπος Widget',
    'Module Name' => 'Όνομα Module',
    'Widget Name' => 'Όνομα Widget',
    'Widget class' => 'Widget class',
    'Description' => 'Περιγραφή',
    'The Widgets caregorized to Frontend and Backend environment ( and Module tabs ) by Module Name that exist within Position' => 'Τα Widgets έχουν ταξινομηθεί στο περιβάλλον Frontend και Backend (και στις καρτέλες Module) από το όνομα του Widget που υπάρχει στη Position',
    'The Position may belong to a different Module Name than the module name that exists within the Widget type' => 'Η θέση μπορεί να ανήκει σε διαφορετικό Module name από το Module name που υπάρχει μέσα στον τύπο του Widget',
];
