<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => '',
    ' Create' => '',
    ' Update' => '',
    'Are you sure you want to delete this item?' => '',
    'Class {class} cannot exist' => '',
    'Create' => '',
    'Create Position' => '',
    'Create Types' => '',
    'Create Widget' => '',
    'Create new Position' => '',
    'Create new Type' => '',
    'Create new widget' => '',
    'Delete' => '',
    'Description' => '',
    'Environment' => '',
    'List of Positions' => '',
    'List of Widgets' => '',
    'List of Widgets Types' => '',
    'Module Name' => '',
    'Name' => '',
    'No sort order found for Position : {id} ' => '',
    'Not found widgets for Position : {id} ' => '',
    'Position' => '',
    'Position : {id} created' => '',
    'Position : {id} deleted' => '',
    'Position : {id} updated' => '',
    'Position : {id} updated !' => '',
    'Position ID' => '',
    'Positions' => '',
    'Positions Sort Order' => '',
    'Publish' => '',
    'Published' => '',
    'Rebuild' => '',
    'Rebuild All Positions ! ' => '',
    'Rebuild Position {id} ! ' => '',
    'Rebuild Sort Order' => '',
    'Select...' => '',
    'Sort Order' => '',
    'The requested page does not exist.' => '',
    'Type : {type} created' => '',
    'Type : {type} deleted' => '',
    'Type : {type} updated' => '',
    'Unpublished' => '',
    'Update' => '',
    'Update Position' => '',
    'Update Position Sort Order' => '',
    'Update Types' => '',
    'Update Widgets' => '',
    'View Position : {title}' => '',
    'View Widget : {title} ' => '',
    'View Widget Type : {title} ' => '',
    'Widget : {id} created ! ' => '',
    'Widget : {id} deleted ! ' => '',
    'Widget : {id} updated ! ' => '',
    'Widget Name' => '',
    'Widget Sort Order' => '',
    'Widget Type' => '',
    'Widget Type ID' => '',
    'Widget Types' => '',
    'Widget class' => '',
    'Widgets' => '',
    'Widgets Types' => '',
    'Widgets with position : {name} ' => '',
    'Widgets with type : {type} ' => '',
    'json in config not Valid' => '',
];
